"""empty message

Revision ID: 27792c695d9b
Revises: 4a0b67705830
Create Date: 2020-01-19 06:55:04.088166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27792c695d9b'
down_revision = '4a0b67705830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
