"""empty message

Revision ID: 70bf8ab4aad9
Revises: a99af3bf08eb
Create Date: 2020-01-16 16:09:19.243251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bf8ab4aad9'
down_revision = 'a99af3bf08eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Modified to make sure the existing data is not affected
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # Execute an update using sql command on the existing table
    op.execute('UPDATE todos set completed = False where completed is null;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
