"""empty message

Revision ID: e2e4df792ea6
Revises: 07cd52cf4567
Create Date: 2020-01-19 07:19:36.041755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e4df792ea6'
down_revision = '07cd52cf4567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Added the line to make sure the existing data is not affected
    op.execute('update todos set completed=False where completed is NULL')
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
