"""empty message

Revision ID: 3de6c9734ad7
Revises: 9d58e11f784f
Create Date: 2020-01-26 08:27:42.334302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de6c9734ad7'
down_revision = '9d58e11f784f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('artist_image_link', sa.String(length=150), nullable=True),
    sa.Column('start_time', sa.String(length=100), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('show_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
