"""empty message

Revision ID: 9d58e11f784f
Revises: ada0153e1cc3
Create Date: 2020-01-25 21:28:54.012267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d58e11f784f'
down_revision = 'ada0153e1cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed auto generated commands for this migration as there is data in the table
    # op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    # op.drop_column('Artist', 'seeking_talent')
    op.alter_column('Artist', 'seeking_talent', new_column_name='seeking_venues')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.drop_column('Artist', 'seeking_venues')
    # Also removing the autogenerated downgrade code
    op.alter_column('Artist', 'seeking_venues', new_column_name='seeking_talent')
    # ### end Alembic commands ###
